///*
// * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
// * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
// */
//package View;
//
//
//import ItemDTO.ItemDto;
//import java.util.ArrayList;
//import java.util.logging.Level;
//import java.util.logging.Logger;
//import javax.swing.JOptionPane;
//import javax.swing.table.DefaultTableModel;
//
///**
// *
// * @author goyum
// */
//public class itemView extends javax.swing.JFrame {
//    
//    private ItemController itemController;
//    /**
//     * Creates new form itemView
//     */
//    public itemView() throws Exception {
//        initComponents();
//        itemController = new ItemController();
//        loadTable();
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//    private void initComponents() {
//
//        lblTitle = new javax.swing.JLabel();
//        lblCode = new javax.swing.JLabel();
//        txtCode = new javax.swing.JTextField();
//        txtDescription = new javax.swing.JTextField();
//        lblDescription = new javax.swing.JLabel();
//        txtUnitPrice = new javax.swing.JTextField();
//        txtQoh = new javax.swing.JTextField();
//        lblQoH = new javax.swing.JLabel();
//        lblUnitPrice = new javax.swing.JLabel();
//        lblPack = new javax.swing.JLabel();
//        txtPack = new javax.swing.JTextField();
//        btnUpdate = new javax.swing.JButton();
//        btnSave1 = new javax.swing.JButton();
//        btnDelete = new javax.swing.JButton();
//        tblItem = new javax.swing.JScrollPane();
//        jTable1 = new javax.swing.JTable();
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//
//        lblTitle.setBackground(new java.awt.Color(204, 204, 204));
//        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
//        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
//        lblTitle.setText("Item Form");
//        lblTitle.setToolTipText("");
//
//        lblCode.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
//        lblCode.setText("Code :");
//
//        txtCode.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
//        txtCode.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                txtCodeActionPerformed(evt);
//            }
//        });
//
//        txtDescription.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
//        txtDescription.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                txtDescriptionActionPerformed(evt);
//            }
//        });
//
//        lblDescription.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
//        lblDescription.setText("Description :");
//
//        txtUnitPrice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
//        txtUnitPrice.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                txtUnitPriceActionPerformed(evt);
//            }
//        });
//
//        txtQoh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
//        txtQoh.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                txtQohActionPerformed(evt);
//            }
//        });
//
//        lblQoH.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
//        lblQoH.setText("QoH :");
//
//        lblUnitPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
//        lblUnitPrice.setText("Unit Price :");
//
//        lblPack.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
//        lblPack.setText("Pack Size :");
//
//        txtPack.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
//        txtPack.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                txtPackActionPerformed(evt);
//            }
//        });
//
//        btnUpdate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
//        btnUpdate.setText("Update");
//        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnUpdateActionPerformed(evt);
//            }
//        });
//
//        btnSave1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
//        btnSave1.setText("Save");
//        btnSave1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnSave1ActionPerformed(evt);
//            }
//        });
//
//        btnDelete.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
//        btnDelete.setText("Delete");
//        btnDelete.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnDeleteActionPerformed(evt);
//            }
//        });
//
//        jTable1.setModel(new javax.swing.table.DefaultTableModel(
//            new Object [][] {
//                {null, null, null, null},
//                {null, null, null, null},
//                {null, null, null, null},
//                {null, null, null, null}
//            },
//            new String [] {
//                "Title 1", "Title 2", "Title 3", "Title 4"
//            }
//        ));
//        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
//            public void mouseClicked(java.awt.event.MouseEvent evt) {
//                jTable1MouseClicked(evt);
//            }
//        });
//        tblItem.setViewportView(jTable1);
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//            .addGroup(layout.createSequentialGroup()
//                .addContainerGap()
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(layout.createSequentialGroup()
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addGroup(layout.createSequentialGroup()
//                                .addComponent(lblDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addGap(93, 93, 93))
//                            .addGroup(layout.createSequentialGroup()
//                                .addComponent(lblCode, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addGap(18, 18, 18)))
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addGroup(layout.createSequentialGroup()
//                                .addComponent(lblUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                .addComponent(txtUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
//                            .addGroup(layout.createSequentialGroup()
//                                .addComponent(lblQoH, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                .addComponent(txtQoh, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                        .addGap(53, 53, 53))
//                    .addGroup(layout.createSequentialGroup()
//                        .addComponent(lblPack, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(txtPack, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                        .addComponent(btnDelete)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(btnSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addGap(24, 24, 24))
//                    .addGroup(layout.createSequentialGroup()
//                        .addGap(42, 42, 42)
//                        .addComponent(tblItem, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(18, 18, 18)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(layout.createSequentialGroup()
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                            .addComponent(lblCode, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
//                            .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                            .addComponent(lblDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
//                            .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                    .addGroup(layout.createSequentialGroup()
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                            .addComponent(lblUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
//                            .addComponent(txtUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addComponent(lblQoH, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
//                            .addComponent(txtQoh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(layout.createSequentialGroup()
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                            .addComponent(lblPack, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
//                            .addComponent(txtPack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                    .addGroup(layout.createSequentialGroup()
//                        .addGap(34, 34, 34)
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                            .addComponent(btnUpdate)
//                            .addComponent(btnDelete)
//                            .addComponent(btnSave1))))
//                .addGap(18, 18, 18)
//                .addComponent(tblItem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addContainerGap(36, Short.MAX_VALUE))
//        );
//
//        pack();
//    }// </editor-fold>//GEN-END:initComponents
//
//    private void txtCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeActionPerformed
//        // TODO add your handling code here:
//    }//GEN-LAST:event_txtCodeActionPerformed
//
//    private void txtDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescriptionActionPerformed
//        // TODO add your handling code here:
//    }//GEN-LAST:event_txtDescriptionActionPerformed
//
//    private void txtUnitPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnitPriceActionPerformed
//        // TODO add your handling code here:
//    }//GEN-LAST:event_txtUnitPriceActionPerformed
//
//    private void txtQohActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQohActionPerformed
//        // TODO add your handling code here:
//    }//GEN-LAST:event_txtQohActionPerformed
//
//    private void txtPackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPackActionPerformed
//        // TODO add your handling code here:
//    }//GEN-LAST:event_txtPackActionPerformed
//
//    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
//         UpdateItem();           
//    }//GEN-LAST:event_btnUpdateActionPerformed
//
//    private void btnSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave1ActionPerformed
//        saveItem();        // TODO add your handling code here:
//    }//GEN-LAST:event_btnSave1ActionPerformed
//
//    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
//        searchItem();        // TODO add your handling code here:
//    }//GEN-LAST:event_jTable1MouseClicked
//
//    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
//        deleteItem();        // TODO add your handling code here:
//    }//GEN-LAST:event_btnDeleteActionPerformed
//
//    /**
//     * @param args the command line arguments
//     */
////    public static void main(String args[]) {
////        /* Set the Nimbus look and feel */
////        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
////        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
////         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
////         */
////        try {
////            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
////                if ("Nimbus".equals(info.getName())) {
////                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
////                    break;
////                }
////            }
////        } catch (ClassNotFoundException ex) {
////            java.util.logging.Logger.getLogger(itemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        } catch (InstantiationException ex) {
////            java.util.logging.Logger.getLogger(itemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        } catch (IllegalAccessException ex) {
////            java.util.logging.Logger.getLogger(itemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
////            java.util.logging.Logger.getLogger(itemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        }
////        //</editor-fold>
////
////        /* Create and display the form */
////        java.awt.EventQueue.invokeLater(new Runnable() {
////            public void run() {
////                new itemView().setVisible(true);
////            }
////        });
////    }
//
//    // Variables declaration - do not modify//GEN-BEGIN:variables
//    private javax.swing.JButton btnDelete;
//    private javax.swing.JButton btnSave1;
//    private javax.swing.JButton btnUpdate;
//    private javax.swing.JTable jTable1;
//    private javax.swing.JLabel lblCode;
//    private javax.swing.JLabel lblDescription;
//    private javax.swing.JLabel lblPack;
//    private javax.swing.JLabel lblQoH;
//    private javax.swing.JLabel lblTitle;
//    private javax.swing.JLabel lblUnitPrice;
//    private javax.swing.JScrollPane tblItem;
//    private javax.swing.JTextField txtCode;
//    private javax.swing.JTextField txtDescription;
//    private javax.swing.JTextField txtPack;
//    private javax.swing.JTextField txtQoh;
//    private javax.swing.JTextField txtUnitPrice;
//    // End of variables declaration//GEN-END:variables
//    private void saveItem(){
//        try {
//        ItemDto dto = new ItemDto(txtCode.getText(), txtDescription.getText(), txtPack.getText(), Double.parseDouble(txtUnitPrice.getText()), Integer.parseInt(txtQoh.getText()));
//        String resp;
//        
//            resp = itemController.saveItem(dto);
//            JOptionPane.showMessageDialog(this, resp);
//            clearForm();
//            loadTable();
//            
//        } catch (Exception ex) {
//            JOptionPane.showMessageDialog(this, "Error. Try entering correct data!");
//        }
//        
//    }
//    
//    private void clearForm(){
//        
//        txtCode.setText("");
//        txtDescription.setText("");
//        txtPack.setText("");
//        txtUnitPrice.setText("");
//        txtQoh.setText("");
//    }
//    private void loadTable(){
//        
//        try{
//           String columns[]  ={"Item Id", "Item Description", "Pack Size", "Unit Price", "QoH"}; 
//            DefaultTableModel dtm = new DefaultTableModel(columns, 0){
//                @Override
//                public boolean isCellEditable(int row, int column){
//                    return false;
//                }
//            };
//          jTable1.setModel(dtm);
//          
//            ArrayList<ItemDto> itemDtos = itemController.getAllItem();
//            
//            for(ItemDto dto : itemDtos){
//                Object[] rowData = {dto.getCode(), dto.getDescription(), dto.getPackSize(), dto.getUnitPrice(), dto.getQoh() };
//                dtm.addRow(rowData);
//            }
//        }
//        catch (Exception e){
//            
//           JOptionPane.showMessageDialog(this, "Error loading Item Data");
//    }
//}
//
//    private void searchItem() {
//        try {
//            String itemId = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
//            ItemDto dto = itemController.searchItem(itemId);
//            
//            if (dto != null){
//                txtCode.setText(dto.getCode());
//                txtDescription.setText(dto.getDescription());
//                txtPack.setText(dto.getPackSize());
//                txtUnitPrice.setText(Double.toString(dto.getUnitPrice()));
//                txtQoh.setText(Integer.toString(dto.getQoh()));
//            } else {
//                JOptionPane.showConfirmDialog(this, "Item not found");
//            }
//            
//        } catch (Exception e) {
//            JOptionPane.showConfirmDialog(this, "Error at loading Data !");
//        }
//        
//    }
//
//    private void deleteItem() {
//        try {
//            String itemCode = txtCode.getText();
//            String resp = itemController.deleteItem(itemCode);
//            JOptionPane.showConfirmDialog(this, "Successfully Deleted!");
//            clearForm();
//            loadTable();
//        } catch (Exception e) {
//            JOptionPane.showConfirmDialog(this, "Error at deleting Data !");
//        }
//    }
//
//    private void UpdateItem() {
//        try {
//            ItemDto itemdto = new ItemDto(txtCode.getText(), txtDescription.getText(), txtPack.getText(), Double.parseDouble(txtUnitPrice.getText()), Integer.parseInt(txtQoh.getText()));
//            String resp = itemController.updateItem(itemdto);
//            JOptionPane.showConfirmDialog(this, resp);
//            clearForm();
//            loadTable();
//            
//        } catch (Exception e) {
//            JOptionPane.showConfirmDialog(this, "Error at updating Data !");
//        }
//    }
//}
